export const doc_template = {
    companyId: 0,
    rootDomain: '',
    domainUrl: '',
    hostUrl: '',
    websocketUrl: '',
    serviceUrl: '',
    authToken: '',
    userName: '',
    domainName: '',
    domain: '',
    serviceName: '',
    password: '',
    feature: '',
    active: '',
    DataSkjema: '',
    xml: '',
    KommandoSkjema: '',
    cmdxml: '',
    webjs: '',
    timeForChannelRequest: '',
    desc: '',
    masterScript: '',
    preMasterScript: '',
    searchTerms: '',
    instance: '',
    mapID: '',
    objectID: '',
    refobjectID: '',
    refDomain: '',
    refService: '',
    LinkSkjema: '',
    links:
      '',
    newUserName: '',
    quantity: '',
    transactiontimeout: '',
    sendGhost: '',
    receiveGhost: '',
  };

  const company_template = {
    id: 1234,
    name: 'IBM',
    orgnr: 999888777,
    contact_person: 'Reodor Felgen',
    email: 'olebrum@hundremeterskogen.am',
    telephone: '19283746',
  };

  const _doc_template = {
    companyId: 1234,
    rootDomain: 'norhive.com',
    domainUrl: '',
    hostUrl: '',
    websocketUrl: '',
    serviceUrl: '',
    authToken: 'lk34jroi2jdvllASLDKJF2sfSDFH2jloijr2o3ndf',
    userName: 'faciliate@synxdns.com',
    domainName: 'faciliate',
    domain: 'faciliate',
    serviceName: 'swg2',
    password: 'passwordFaciliate24',
    feature: 'd',
    active: 'true',
    DataSkjema: '',
    xml: '<rtw></rtw>',
    KommandoSkjema: '',
    cmdxml: '<cmd></cmd>',
    webjs: '',
    timeForChannelRequest: '86000',
    desc: 'test swg2',
    masterScript: '',
    preMasterScript: '',
    searchTerms: '',
    instance: '3',
    mapID: '',
    objectID: '2',
    refobjectID: '',
    refDomain: '',
    refService: '',
    LinkSkjema: '',
    links:
      '<xml><links><link><uri>gateway/dash7</uri><active>true</active></link></links></xml>',
    newUserName: '',
    quantity: '5',
    transactiontimeout: '24',
    sendGhost: '1',
    receiveGhost: '3',
  };